kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: grafana
  namespace: prometheus
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                namespace: prometheus
                port:
                  number: 80