kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: grafana
  namespace: prometheus
  annotations:
    # spec.ingressClassName: traefik # This was an incorrect placement for ingressClassName
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: kube.local
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80