kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: prometheus-exporter
  namespace: prometheus
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - http:
        paths:
          - path: /exporter
            pathType: Prefix
            backend:
              service:
                name: prometheus-prometheus-node-exporter
                port:
                  number: 9100