kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: prometheus
  namespace: prometheus
spec:
  ingressClassName: traefik # Correct field for specifying the Ingress controller
  rules:
   - host: kube.local
      http:
        paths:
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090