kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - http:
        paths:
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090