apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: traefik
spec:
  endpoints:
  - port: web
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: traefik